# Generated by Django 3.2 on 2021-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_scheduling_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_date',
            field=models.DateTimeField(),
        ),
    ]
