# Generated by Django 3.2 on 2021-04-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_scheduling_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='done',
        ),
    ]
