# Generated by Django 3.2 on 2021-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_scheduling_scheduling_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_done',
            field=models.CharField(max_length=20),
        ),
    ]
